trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_Run_tests
  displayName: Build && Run tests ina
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'DockerHub'
        dockerComposeFile: './docker-compose.test.yaml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up --abort-on-container-exit'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/hello_world_ci-report_file_test.xml'