name: GitHub Ci-CD Test Project
run-name: ${{ github.actor }} has create a pull request for branch ${{ github.ref }}.
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting pipeline with a ${{ github.event_name }} event."
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo "Code has been checkout."
      - name: Use node v18
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: echo "Use node version 18"
      - name: Running install
        run: |
          echo "Start dependencies installation"
          npm install
      - run: echo "Dependencies has been instaleld"
      - name: Running lint
        run: |
          echo "Start running lint"
          npm run lint
      - run: echo "Lint ok."
      - name: Running Tests
        run: |
          echo "Start running tests"
          npm run test
      - run: echo "Tests ok."
      - name: Building projects
        run: |
          echo "Start building projects"
          npm run build
      - run: echo "Build ok."
      - run: echo "This job has ended with status ${{ job.status }}."
